INSERT INTO `oxconfig` (`OXID`, `OXSHOPID`, `OXMODULE`, `OXVARNAME`, `OXVARTYPE`, `OXVARVALUE`, `OXTIMESTAMP`) VALUES
#Group display:
md5(uuid()),	1,	'theme:wave',	'blFullwidthLayout',	'bool',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'blHomeLink',	'bool',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'bl_showManufacturerSlider',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'sDefaultListDisplayType',	'select',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'blShowListDisplayType',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'sStartPageListDisplayType',	'select',	'g', NOW()),
md5(uuid()),	1,	'theme:wave',	'aNrofCatArticles',	'arr',	'a', NOW()),
md5(uuid()),	1,	'theme:wave',	'aNrofCatArticlesInGrid',	'arr',	'a', NOW()),
md5(uuid()),	1,	'theme:wave',	'iNewBasketItemMessage',	'select',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'blShowFinalStep',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blShowBirthdayFields',	'bool',	'1', NOW()),
#Group logo:
md5(uuid()),	1,	'theme:wave',	'sLogoFile',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sLogoWidth',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sLogoHeight',	'str',	'', NOW()),
#Group favicon:
md5(uuid()),	1,	'theme:wave',	'sFaviconFile',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFavicon16File',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFavicon32File',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFavicon48File',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFavicon64File',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFavicon128File',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFavicon512File',	'str',	'favi', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFaviconMSTileColor',	'str',	'', NOW()),
#Group images:
md5(uuid()),	1,	'theme:wave',	'sIconsize',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sThumbnailsize',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'aDetailImageSizes',	'aarr',	'a', NOW()),
md5(uuid()),	1,	'theme:wave',	'sZoomImageSize',	'str',	'665*', NOW()),
md5(uuid()),	1,	'theme:wave',	'sCatIconsize',	'str',	'16', NOW()),
md5(uuid()),	1,	'theme:wave',	'sCatPromotionsize',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sCatThumbnailsize',	'str',	'11', NOW()),
md5(uuid()),	1,	'theme:wave',	'sManufacturerIconsize',	'str',	'100*100', NOW()),
md5(uuid()),	1,	'theme:wave',	'blSliderShowImageCaption',	'bool',	'1', NOW()),
#Group background:
md5(uuid()),	1,	'theme:wave',	'sBackgroundColor',	'str',	'#C', NOW()),
md5(uuid()),	1,	'theme:wave',	'blUseBackground',	'bool',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sBackgroundPath',	'str',	'm', NOW()),
md5(uuid()),	1,	'theme:wave',	'sBackgroundSize',	'select',	'cover', NOW()),
md5(uuid()),	1,	'theme:wave',	'sBackgroundPosHorizontal',	'select',	'c', NOW()),
md5(uuid()),	1,	'theme:wave',	'sBackgroundPosVertical',	'select',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sBackgroundRepeat',	'select',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'blBackgroundAttachment',	'bool',	'1', NOW()),
#Group features:
md5(uuid()),	1,	'theme:wave',	'bl_showCompareList',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'bl_showWishlist',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'bl_showListmania',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'bl_showVouchers',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'bl_showGiftWrapping',	'bool',	'1', NOW()),
#Group footer:
md5(uuid()),	1,	'theme:wave',	'blFooterShowHelp',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blFooterShowLinks',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blFooterShowNews',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blFooterShowNewsletter',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blFooterShowNewsletterForm',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'sFacebookUrl',	'str',	'h', NOW()),
md5(uuid()),	1,	'theme:wave',	'sTwitterUrl',	'str',	'h', NOW()),
md5(uuid()),	1,	'theme:wave',	'sYouTubeUrl',	'str',	'h', NOW()),
md5(uuid()),	1,	'theme:wave',	'sBlogUrl',	'str',	'h', NOW()),
#Group contact:
md5(uuid()),	1,	'theme:wave',	'sGoogleMapsAddr',	'str',	'', NOW()),
#Group emails:
md5(uuid()),	1,	'theme:wave',	'sEmailLogo',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'blEmailsShowProductPictures',	'bool',	'', NOW()),
#Group googleanalytics:
md5(uuid()),	1,	'theme:wave',	'sGATrackingId',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'blUseGAEcommerceTracking',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blUseGAPageTracker',	'bool',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'blGAAnonymizeIPs',	'bool',	'1', NOW()),
#Group googlets:
md5(uuid()),	1,	'theme:wave',	'blUseGoogleTS',	'bool',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sGoogleVendorId',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sPageLanguage',	'str',	'de', NOW()),
md5(uuid()),	1,	'theme:wave',	'sGoogleShoppingAccountId',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sShippingDaysOnStock',	'str',	'', NOW()),
md5(uuid()),	1,	'theme:wave',	'sShippingDaysNotOnStock',	'str',	'5', NOW()),
md5(uuid()),	1,	'theme:wave',	'sDeliveryDaysOnStock',	'str',	'6', NOW()),
md5(uuid()),	1,	'theme:wave',	'sDeliveryDaysNotOnStock',	'str',	'1', NOW()),
md5(uuid()),	1,	'theme:wave',	'sShoppingLanguage',	'str',	'de', NOW()),
md5(uuid()),	1,	'theme:wave',	'sShoppingCountry',	'str',	'', NOW());



INSERT INTO `oxconfigdisplay` (`OXID`, `OXCFGMODULE`, `OXCFGVARNAME`, `OXGROUPING`, `OXVARCONSTRAINT`, `OXPOS`, `OXTIMESTAMP`) VALUES
#Group display:
md5(uuid()), 'theme:wave', 'blFullwidthLayout', 'display', '', 1001, NOW()),
md5(uuid()), 'theme:wave', 'blHomeLink', 'display', '', 1002, NOW()),
md5(uuid()), 'theme:wave', 'bl_showManufacturerSlider', 'display', '', 1003, NOW()),
md5(uuid()), 'theme:wave', 'sDefaultListDisplayType', 'display', 'infogrid|line|grid', 1004, NOW()),
md5(uuid()), 'theme:wave', 'blShowListDisplayType', 'display', '', 1005, NOW()),
md5(uuid()), 'theme:wave', 'sStartPageListDisplayType', 'display', 'infogrid|line|grid', 1006, NOW()),
md5(uuid()), 'theme:wave', 'aNrofCatArticles', 'display', '', 1007, NOW()),
md5(uuid()), 'theme:wave', 'aNrofCatArticlesInGrid', 'display', '', 1008, NOW()),
md5(uuid()), 'theme:wave', 'iNewBasketItemMessage', 'display', '0|1|2|3', 1009, NOW()),
md5(uuid()), 'theme:wave', 'blShowFinalStep', 'display', '', 1010, NOW()),
md5(uuid()), 'theme:wave', 'blShowBirthdayFields', 'display', '', 1011, NOW()),
#Group logo:
md5(uuid()), 'theme:wave', 'sLogoFile', 'logo', '', 1102, NOW()),
md5(uuid()), 'theme:wave', 'sLogoWidth', 'logo', '', 1103, NOW()),
md5(uuid()), 'theme:wave', 'sLogoHeight', 'logo', '', 1104, NOW()),
#Group favicon:
md5(uuid()), 'theme:wave', 'sFaviconFile', 'favicons', '', 1201, NOW()),
md5(uuid()), 'theme:wave', 'sFavicon16File', 'favicons', '', 1202, NOW()),
md5(uuid()), 'theme:wave', 'sFavicon32File', 'favicons', '', 1203, NOW()),
md5(uuid()), 'theme:wave', 'sFavicon48File', 'favicons', '', 1204, NOW()),
md5(uuid()), 'theme:wave', 'sFavicon64File', 'favicons', '', 1205, NOW()),
md5(uuid()), 'theme:wave', 'sFavicon128File', 'favicons', '', 1206, NOW()),
md5(uuid()), 'theme:wave', 'sFavicon512File', 'favicons', '', 1207, NOW()),
md5(uuid()), 'theme:wave', 'sFaviconMSTileColor', 'favicons', '', 1208, NOW()),
#Group images:
md5(uuid()), 'theme:wave', 'sIconsize', 'images', '', 1301, NOW()),
md5(uuid()), 'theme:wave', 'sThumbnailsize', 'images', '', 1302, NOW()),
md5(uuid()), 'theme:wave', 'aDetailImageSizes', 'images', '', 1303, NOW()),
md5(uuid()), 'theme:wave', 'sZoomImageSize', 'images', '', 1304, NOW()),
md5(uuid()), 'theme:wave', 'sCatIconsize', 'images', '', 1305, NOW()),
md5(uuid()), 'theme:wave', 'sCatPromotionsize', 'images', '', 1306, NOW()),
md5(uuid()), 'theme:wave', 'sCatThumbnailsize', 'images', '', 1307, NOW()),
md5(uuid()), 'theme:wave', 'sManufacturerIconsize', 'images', '', 1308, NOW()),
md5(uuid()), 'theme:wave', 'blSliderShowImageCaption', 'images', '', 1309, NOW()),
#Group background:
md5(uuid()), 'theme:wave', 'sBackgroundColor', 'background', '', 1401, NOW()),
md5(uuid()), 'theme:wave', 'blUseBackground', 'background', '', 1402, NOW()),
md5(uuid()), 'theme:wave', 'sBackgroundPath', 'background', '', 1403, NOW()),
md5(uuid()), 'theme:wave', 'sBackgroundSize', 'background', 'cover|contain|normal', 1404, NOW()),
md5(uuid()), 'theme:wave', 'sBackgroundPosHorizontal', 'background', 'left|right|center', 1405, NOW()),
md5(uuid()), 'theme:wave', 'sBackgroundPosVertical', 'background', 'top|bottom|center', 1406, NOW()),
md5(uuid()), 'theme:wave', 'sBackgroundRepeat', 'background', 'no-repeat|repeat-x|repeat-y|repeat', 1407, NOW()),
md5(uuid()), 'theme:wave', 'blBackgroundAttachment', 'background', '', 1408, NOW()),
#Group features:
md5(uuid()), 'theme:wave', 'bl_showCompareList', 'features', '', 1501, NOW()),
md5(uuid()), 'theme:wave', 'bl_showPriceAlarm', 'features', '', 1502, NOW()),
md5(uuid()), 'theme:wave', 'bl_showWishlist', 'features', '', 1503, NOW()),
md5(uuid()), 'theme:wave', 'bl_showListmania', 'features', '', 1504, NOW()),
md5(uuid()), 'theme:wave', 'bl_showVouchers', 'features', '', 1505, NOW()),
md5(uuid()), 'theme:wave', 'bl_showGiftWrapping', 'features', '', 1506, NOW()),
#Group footer:
md5(uuid()), 'theme:wave', 'blFooterShowHelp', 'footer', '', 1601, NOW()),
md5(uuid()), 'theme:wave', 'blFooterShowLinks', 'footer', '', 1602, NOW()),
md5(uuid()), 'theme:wave', 'blFooterShowNews', 'footer', '', 1603, NOW()),
md5(uuid()), 'theme:wave', 'blFooterShowNewsletter', 'footer', '', 1604, NOW()),
md5(uuid()), 'theme:wave', 'blFooterShowNewsletterForm', 'footer', '', 1605, NOW()),
md5(uuid()), 'theme:wave', 'sFacebookUrl', 'footer', '', 1606, NOW()),
md5(uuid()), 'theme:wave', 'sTwitterUrl', 'footer', '', 1607, NOW()),
md5(uuid()), 'theme:wave', 'sYouTubeUrl', 'footer', '', 1608, NOW()),
md5(uuid()), 'theme:wave', 'sBlogUrl', 'footer', '', 1609, NOW()),
#Group contact:
md5(uuid()), 'theme:wave', 'sGoogleMapsAddr', 'contact', '', 1701, NOW()),
#Group email:
md5(uuid()), 'theme:wave', 'sEmailLogo', 'emails', '', 1801, NOW()),
md5(uuid()), 'theme:wave', 'blEmailsShowProductPictures', 'emails', '', 1802, NOW()),
#Group googleanalytics:
md5(uuid()), 'theme:wave', 'sGATrackingId', 'googleanalytics', '', 1901, NOW()),
md5(uuid()), 'theme:wave', 'blUseGAEcommerceTracking', 'googleanalytics', '', 1902, NOW()),
md5(uuid()), 'theme:wave', 'blUseGAPageTracker', 'googleanalytics', '', 1903, NOW()),
md5(uuid()), 'theme:wave', 'blGAAnonymizeIPs', 'googleanalytics', '', 1904, NOW()),
#Group googlets:
md5(uuid()), 'theme:wave', 'blUseGoogleTS', 'googlets', '', 2001, NOW()),
md5(uuid()), 'theme:wave', 'sGoogleVendorId', 'googlets', '', 2002, NOW()),
md5(uuid()), 'theme:wave', 'sPageLanguage', 'googlets', '', 2003, NOW()),
md5(uuid()), 'theme:wave', 'sGoogleShoppingAccountId', 'googlets', '', 2004, NOW()),
md5(uuid()), 'theme:wave', 'sShippingDaysOnStock', 'googlets', '', 2005, NOW()),
md5(uuid()), 'theme:wave', 'sShippingDaysNotOnStock', 'googlets', '', 2006, NOW()),
md5(uuid()), 'theme:wave', 'sDeliveryDaysOnStock', 'googlets', '', 2007, NOW()),
md5(uuid()), 'theme:wave', 'sDeliveryDaysNotOnStock', 'googlets', '', 2008, NOW()),
md5(uuid()), 'theme:wave', 'sShoppingLanguage', 'googlets', '', 2009, NOW()),
md5(uuid()), 'theme:wave', 'sShoppingCountry', 'googlets', '', 2010, NOW());
